### ISSUE TITLE
docker compose で ファイルとしてマウントする方法

### ISSUE THREAD

**Issue by g-kari** [g-kari/0g0-blog#47]
# docker compose で ファイルとしてマウントする方法

## 結果から

けつに :ro つけるだけ

```yaml
services:
  backend:
    image: awesome/backend
    volumes:
      - .env.local:.env:ro
```

# # # # ##
